config/routes.rb
Bonediva::Application.routes.draw do
  resources :bonediva_scaffolds

  resources :users do
    resources :user_categories
    resources :avatars
    resources :paintings
    resources :messages, only: [:new, :create]
    resources :carts do
      resources :cart_items
      resources :orders
    end
  end
  resources :products do
    resources :paintings
    resources :prints
    resources :print_categories
  end
  resources :carts
  resources :paintings
  resources :sessions
  resources :categories
  resources :avatars
  resources :orders
  resources :blog_posts
  resources :sold_products
  resources :messages, only: [:new, :create, :destroy]
  resources :recorders, only: [ :new ]
  resources :print_categories

  root :to => 'main#index'

  match '/index', :to => 'main#index'

  get '/about', :to => 'main#about'
  
  get "log_in" => "sessions#new", :as => "log_in"
  
  get "log_out" => "sessions#destroy", :as => "log_out"

  post '/categories/:id/update_featured_painting/:painting_id', to: 'categories#update_featured_painting', as: 'update_featured_painting'
  
  match '/products/:product_id/paintings/new', to: 'paintings#add_product_painting', as: 'add_product_painting'

  post '/users/:user_id/carts/:cart_id/cart_items/new/:product_id', to: 'cart_items#create', as: 'add_cart_item'

  post '/users/:user_id/cart_items/new/:product_id', to: 'cart_items#create_print', as: 'print_to_cart'

  match '/products/:product_id/paintings/new', to: 'products#add_product_painting', as: 'add_product_painting'
  
  get  '/for_sale_paintings', to: 'products#for_sale_paintings', as: 'for_sale_products'

  post "users/:user_id/carts/:cart_id/cart_items/:id" => "cart_items#destroy", as: "destroy_cart_item"

  post "products/:id", to: "products#destroy", as: "destoy_product"

  post "blog_posts/:id", to: "blog_posts#destroy", as: "destroy_blog_post"

  get "blog_posts/:id/bp_image", to: "blog_posts#bp_image", as: "bp_image"
  get "/aceo", to: "products#aceo", as: "aceo_products"

  get "/aceo/about", to: "products#about_aceo", as: "about_aceo"
  match "/products/:product_id/update_to_sold", to: "products#update_to_sold", as: "sell_product"

  match "/sold_products/:sold_product_id/revert_to_product", to: "sold_products#revert_to_product", as: "revert_to_product"

  match "products/:product_id/set_main_image/:painting_id", to: "products#set_main_image", as: "set_main_image"

  match "sold_products/:sold_product_id/set_sold_main_image/:painting_id", to: "sold_products#set_sold_main_image", as: "set_sold_main_image"
  post "paintings/:id/set_as_home_image", to: "paintings#set_as_home_image", as: "set_as_home_image"

  post "paintings/:id/remove_home_image", to: "paintings#remove_home_image", as: "remove_home_image"

  match 'auth/:facebook/callback', to: 'sessions#facebook'

  match 'auth/failure', to: redirect('/')

end

app/models/sold_product.rb
class SoldProduct < ActiveRecord::Base
 attr_accessible :name, :description, :price, :sold_at, :image, :category_id, 
                  :primary_painting_id, :size, :categories

 belongs_to :user
 has_and_belongs_to_many :categories
 has_many :paintings, as: :paintable 


   def main_image(style)
    #self.paintings.first.image_url(style) rescue nil
    painting = Painting.find(primary_painting_id)
    painting.image_url(style)
  end

  def primary_painting
    painting = Painting.find(primary_painting_id)
  end


  def update_sold_product_to_product
    product = user.products.new(
      name: name,
      description: description,
      size: size,
      price: price,
      primary_painting_id: primary_painting_id,
      categories: categories
      #product_relation_id: id,
   # order_id: order.id
    )
    if product.save
      paintings.map{|e| e.update_attributes(sold_product_id: nil, paintable_type: "Product", paintable_id: product.id)}
      destroy
    end
  end

  def update_to_main_image(painting)
      update_attributes(primary_painting_id: painting.id)
  end

end

app/controllers/sold_products_controller.rb
class SoldProductsController < ApplicationController

  def index
    @sold_products = SoldProduct.order("id DESC").page(params[:page]).per(15)
  end

  def create
    @sold_product = SoldProduct.new(params[:sold_product])
    if @sold_product.save
      redirect_to :root, notice: "Updated to Sold"
    else
      redirect_to :back, notice: "#{@sold_product.errors.full_messages}"
    end
  end

  def edit
    @categories = Category.all
    @product = SoldProduct.find(params[:id])
    @pcats = @product.categories
    @paintings = @product.paintings
    @painting = @product.paintings.new(params[:painting])
    if @painting.save
      @product.update
      redirect_to sold_product_path(@product)
    end
  end

  def update
    @product = SoldProduct.find(params[:id])
    if params[:paintable_id]
      @painting = @product.paintings.find(params[:paintable_id]) 
      if params[:painting][:paintable_id] == @product.id
        @painting.paintable_type = "Product"
        @painting.update
      end
    end
    @product.categories = Category.where(id: params[:categories][:category_id])
    if @product.update_attributes(params[:sold_product])
        @product.paintings.map{|e| e.update_attributes(title: @product.name, description: @product.description)}
        redirect_to sold_product_path(@product), :notice => "your painting has been updated"
    end
  end

  def show
    @sold_product = SoldProduct.find(params[:id])
  end

  def revert_to_product
    @sold_product = SoldProduct.find(params[:sold_product_id])
    if @sold_product.update_sold_product_to_product
      redirect_to :root, notice: "#{@sold_product.name} has been reverted back to a product."
    else
      redirect_to :back, notice: "#{@sold_product.errors.full_messages}"
    end
  end

  def set_sold_main_image
    @sold_product = SoldProduct.find(params[:sold_product_id])
    painting = Painting.find(params[:painting_id])
    if @sold_product.update_to_main_image(painting)
      redirect_to :back, notice: "This painting is now the main image for this product"
    end
  end

  def destroy
    @sold_product = SoldProduct.find(params[:id])
    
  end

end

app/views/sold_products/_display_sold_products.html.erb
<div class="row-fluid">
  <div id="products"> 
    <% @sold_products.each do |product| %>
      <div class="product-list">
        <div class="span4">
          <% if product.class.name == "Product"%>
            <div class="prod-disp" data-product-id=<%= product.id %>>
          <% elsif product.class.name == "SoldProduct" %>
            <div class="sold-prod-disp" data-product-id=<%= product.id %>>
          <% end %>
            <div class="painting-display" itemscope itemtype="http://schema.org/SoldProduct">
              <div class="span12">
                <div class="top">
                  <div class="span6">
                    <div class="painting1">
                      <% if product.paintings.present? %>
                        <% if product.class.name == "Product"%>
                          <%=  link_to (image_tag (product.main_image(:standard)), alt: product.name, title: product.name, itemprop: "image"), product_path(product) %></br>
                        <% elsif product.class.name == "SoldProduct" %>
                          <%=  link_to (image_tag (product.main_image(:standard)), alt: "'#{product.name}' by Lisa Luree", title: "'#{product.name} by Lisa Luree", itemprop: "image"), sold_product_path(product) %></br>
                        <% end %>
                      <% end %>
                    </div>
                  </div>
                  <div class="span6">
                    <div class="info">
                      <div class="span12">
                        <div class="name">
                          <% if product.class.name == "Product"%>
                              Name: <%= link_to truncate(product.name, length: 15), product_path(product), itemprop: "name" %>
                          <% elsif product.class.name == "SoldProduct" %>
                              Name: <%= link_to truncate(product.name, length: 15), sold_product_path(product), itemprop: "name" %>
                          <% end %>
                        </div>
                      </div>
                      <div class="span12">
                        <div id="price">
                          <div class="span10">Price: <%= number_to_currency product.price %></div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="span12">
                <div id="cart-button">
                  <div style="float:right">
                    <% if product.class.name == "Product" %>
                      <%= button_to "Add To Cart", add_cart_item_path(current_user, current_user.carts.last, product), id: "button1" if current_user.present? %>
                    <% else %>
                      <strong>Sold-</strong><%= product.created_at.strftime("%m/%d/%Y") %>
                    <% end %>
                  </div>
                </div>
              </div>
              <div id="admin-function">
                <% if product.paintings.any? %>
                  <% if is_admin? %>
                    <%if @category.present? %>
                      <div class="span4">
                        <%= link_to "Add as featured", category_path(@category, category: { featured_painting_id: product.paintings.first.id}), data: { method: :put } %>
                      </div>
                    <% else %>
                      <%= nil %>
                    <% end %>
                      <div class="span3"><%= link_to "Delete", product, data: {confirm: "Are you sure you want to delete #{ product.name }?", method: :delete, remote: true } %></div>
                      <div class="span4 offset1"><%= link_to "Edit Product", edit_product_path(product)  %></div>
                  <% end %>
                <% end %>
              </div>
              <div id="description">
                <div class="span10">
                  <u><b>Description:</b></u><p itemprop="description"><%= truncate(product.description, length: 75 ) %></p></br>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div> 
    <% end %>
  </div>



</div>

  <%= paginate @sold_products %>

app/views/sold_products/edit.html.erb
<h3> Current Info </h3>
<div id="mid_component">
  <div class="row-fluid">
    <div class="span12">
      <div id="edit-page">
        <div class="span6">
          <div id="left-side">
            <div id="name">
              <div class="span6">Name:</div>
              <div class="span6"><%= @product.name %></div>
            </div>
            <div id="description">
              <div class="span6">Description:</div>
              <div class="span6"><%= @product.description %></div>
            </div>
            <div id="price">
              <div class="span6">Price:</div>
              <div class="span6"><%= @product.price %></div>
            </div>
            <div id="size">
              <div class="span6">Size:</div>
              <div class="span6"><%= @product.size %></div>
            </div>
          </div>
        </div>
        <div class="span6">
          <div id="right-side">
            <div class="span12">
              <div id="painting-holder">
                <% @paintings.each do |p| %>
                  <div class="span3">
                    <div id="paintings">
                      <div class="thumbnails">
                        <div class="thumbnail"> 
                          <%= link_to (image_tag p.image_url(:thumb)) %>
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>

        <div class="span12">
          <div id="edit-form">
            <%= render :partial => "products/product_form" %>
          </div>
        </div>
        <div class="span8">
          <div id="add_painting_form">
            <div class="span12">
              <h5 id="head-description">
                (Upload Another Painting To You're Product)
              </h5>
              <div id="paint-form">
                <div class="span12">
                  <%= render partial: "paintings/add_painting_form" %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/sold_products/index.html.erb
<h2 class="span6 offset4 h-head">Lisa Luree's Artwork</h2>
<div class="span12">
  <div class="mid_component">
    <% if @sold_products.present?%>
      <%= render partial: "sold_products/display_sold_products"%>
    <% else %>
      <h4> Sorry no Available Products</h4>
    <% end%>
  </div>
</div>

app/views/sold_products/show.html.erb
<% content_for :head do %>
  <%= tag :meta, property: "fb:app_id", content: ENV["FACEBOOK_APP_ID"] %>
  <%= tag :meta, property: "og:site_name", content: "Lisa Luree -Bonediva" %>
  <%= tag :meta, property: "og:type", content: "bonediva:sold_product" %>
  <%= tag :meta, property: "og:title", content: @sold_product.name %>
  <%= tag :meta, property: "og:url", content: sold_product_url(@sold_product) %>
  <%= tag :meta, property: "og:description", content: "#{@sold_product.description} \n Sold Date: #{@sold_product.created_at} \n Size: #{@sold_product.size}" %>
  <%= tag :meta, property: "og:image", content: image_path(@sold_product.main_image(:home)) %>
<% end %>

<%= render partial: "products/show_product", locals: {product: @sold_product}%>