config/routes.rb
Bonediva::Application.routes.draw do
  resources :bonediva_scaffolds

  resources :users do
    resources :user_categories
    resources :avatars
    resources :paintings
    resources :messages, only: [:new, :create]
    resources :carts do
      resources :cart_items
      resources :orders
    end
  end
  resources :products do
    resources :paintings
    resources :prints
    resources :print_categories
  end
  resources :carts
  resources :paintings
  resources :sessions
  resources :categories
  resources :avatars
  resources :orders
  resources :blog_posts
  resources :sold_products
  resources :messages, only: [:new, :create, :destroy]
  resources :recorders, only: [ :new ]
  resources :print_categories

  root :to => 'main#index'

  match '/index', :to => 'main#index'

  get '/about', :to => 'main#about'
  
  get "log_in" => "sessions#new", :as => "log_in"
  
  get "log_out" => "sessions#destroy", :as => "log_out"

  post '/categories/:id/update_featured_painting/:painting_id', to: 'categories#update_featured_painting', as: 'update_featured_painting'
  
  match '/products/:product_id/paintings/new', to: 'paintings#add_product_painting', as: 'add_product_painting'

  post '/users/:user_id/carts/:cart_id/cart_items/new/:product_id', to: 'cart_items#create', as: 'add_cart_item'

  post '/users/:user_id/cart_items/new/:product_id', to: 'cart_items#create_print', as: 'print_to_cart'

  match '/products/:product_id/paintings/new', to: 'products#add_product_painting', as: 'add_product_painting'
  
  get  '/for_sale_paintings', to: 'products#for_sale_paintings', as: 'for_sale_products'

  post "users/:user_id/carts/:cart_id/cart_items/:id" => "cart_items#destroy", as: "destroy_cart_item"

  post "products/:id", to: "products#destroy", as: "destoy_product"

  post "blog_posts/:id", to: "blog_posts#destroy", as: "destroy_blog_post"

  get "blog_posts/:id/bp_image", to: "blog_posts#bp_image", as: "bp_image"
  get "/aceo", to: "products#aceo", as: "aceo_products"

  get "/aceo/about", to: "products#about_aceo", as: "about_aceo"
  match "/products/:product_id/update_to_sold", to: "products#update_to_sold", as: "sell_product"

  match "/sold_products/:sold_product_id/revert_to_product", to: "sold_products#revert_to_product", as: "revert_to_product"

  match "products/:product_id/set_main_image/:painting_id", to: "products#set_main_image", as: "set_main_image"

  match "sold_products/:sold_product_id/set_sold_main_image/:painting_id", to: "sold_products#set_sold_main_image", as: "set_sold_main_image"
  post "paintings/:id/set_as_home_image", to: "paintings#set_as_home_image", as: "set_as_home_image"

  post "paintings/:id/remove_home_image", to: "paintings#remove_home_image", as: "remove_home_image"

  match 'auth/:facebook/callback', to: 'sessions#facebook'

  match 'auth/failure', to: redirect('/')

end

app/models/cart.rb
class Cart < ActiveRecord::Base

  #validates :product_id, presence: true, uniqueness: { scope: [:cart_id] }

  has_many :cart_items
  has_many :products, through: :cart_items
  has_many :prints, through: :cart_items
  has_many :sold_products
  has_one :order
  belongs_to :user
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  respond_to :html, :js, :json

  before_filter :find_user, only: [:destoy]
  before_filter :cart_total_price, only: [:show, :create, :update]

  def new
    
  end

  def create
    @cart = Cart.new(params[:cart])
  end

  def show
    @cart_items = @cart.cart_items
    @products 
  end

  def update
    if @cart.order.new?
      @cart.total_price = @total_price
    end
  end

  def destroy
    respond_with @cart
  end

  private

  def cart_total_price
    @cart = Cart.find(params[:id])
    @total_price = CartItem.where(cart_id: @cart.id).sum(:price)
  end

  def find_user
    @user = User.find(params[:user_id])
  end
end

app/views/carts/_cart_items.html.erb
<div class="row-fluid">
  <div id="list-box">
    <div style="text-align:center">
      <h4>
        <%= "Here is your cart #{current_user.name}"%>
      </h4>
    </div>
  </div>
  <% @cart_items.each do |item| %>
      <div class="cart-items">
        <div class="span12">
          <div class="cart-item">

        <div class="cart-item-name">
          <div class="span4"><%= item.name %></div>
        </div>

        <div class="cart-item-price">
          <% if item.present? %>
          <div class="span2"><%= number_to_currency item.price %></div>
        <% else%>
          00.00
        <%end%>
        </div>

        <div class="span3">
          <div class="cart-item-painting">
            <div class="span6">
              <div class="thumbnails">
                <div class="thumbnail">
                  <% if item.product.present?%>
                    <%= image_tag item.product.main_image(:thumb) %>
                  <% else %>
                    This Product is not avalable
                  <% end %>
                  
                </div>
              </div>
            </div>i
          </div>
        </div>

        <div class="cart-item-button">
          <div class"span2">  <%= button_to 'remove', user_cart_cart_item_path(current_user, @cart, item), id: "button1", data: { confirm: "Do you want to delete #{item.name}?", method: :delete, remote: true } %></div>
        </div>

        </div>
      </div>
    </div>
  <% end %>
  <div class="span12">
    <div id="checkout-list">
        <div id="total-box">
          <h4>
            <div class="span4">Total:</div>
            <div class="span4"><%= number_to_currency @total_price %></div>
            <div class="span4"><%= link_to "Checkout", new_user_cart_order_path(current_user, current_user.carts.last), id: "button1" %></div>
          </h4>
        </div>
    </div>
  </div>
</div>

app/views/carts/destroy.js.erb
$("#cart_item-<%=@cart_item.id%>").remove() 

app/views/carts/show.html.erb
<div class="mid_component">
  <%= render partial: "cart_items" %>
</div>