config/routes.rb
Bonediva::Application.routes.draw do
  resources :bonediva_scaffolds

  resources :users do
    resources :user_categories
    resources :avatars
    resources :paintings
    resources :messages, only: [:new, :create]
    resources :carts do
      resources :cart_items
      resources :orders
    end
  end
  resources :products do
    resources :paintings
    resources :prints
    resources :print_categories
  end
  resources :carts
  resources :paintings
  resources :sessions
  resources :categories
  resources :avatars
  resources :orders
  resources :blog_posts
  resources :sold_products
  resources :messages, only: [:new, :create, :destroy]
  resources :recorders, only: [ :new ]
  resources :print_categories

  root :to => 'main#index'

  match '/index', :to => 'main#index'

  get '/about', :to => 'main#about'
  
  get "log_in" => "sessions#new", :as => "log_in"
  
  get "log_out" => "sessions#destroy", :as => "log_out"

  post '/categories/:id/update_featured_painting/:painting_id', to: 'categories#update_featured_painting', as: 'update_featured_painting'
  
  match '/products/:product_id/paintings/new', to: 'paintings#add_product_painting', as: 'add_product_painting'

  post '/users/:user_id/carts/:cart_id/cart_items/new/:product_id', to: 'cart_items#create', as: 'add_cart_item'

  post '/users/:user_id/cart_items/new/:product_id', to: 'cart_items#create_print', as: 'print_to_cart'

  match '/products/:product_id/paintings/new', to: 'products#add_product_painting', as: 'add_product_painting'
  
  get  '/for_sale_paintings', to: 'products#for_sale_paintings', as: 'for_sale_products'

  post "users/:user_id/carts/:cart_id/cart_items/:id" => "cart_items#destroy", as: "destroy_cart_item"

  post "products/:id", to: "products#destroy", as: "destoy_product"

  post "blog_posts/:id", to: "blog_posts#destroy", as: "destroy_blog_post"

  get "blog_posts/:id/bp_image", to: "blog_posts#bp_image", as: "bp_image"
  get "/aceo", to: "products#aceo", as: "aceo_products"

  get "/aceo/about", to: "products#about_aceo", as: "about_aceo"
  match "/products/:product_id/update_to_sold", to: "products#update_to_sold", as: "sell_product"

  match "/sold_products/:sold_product_id/revert_to_product", to: "sold_products#revert_to_product", as: "revert_to_product"

  match "products/:product_id/set_main_image/:painting_id", to: "products#set_main_image", as: "set_main_image"

  match "sold_products/:sold_product_id/set_sold_main_image/:painting_id", to: "sold_products#set_sold_main_image", as: "set_sold_main_image"
  post "paintings/:id/set_as_home_image", to: "paintings#set_as_home_image", as: "set_as_home_image"

  post "paintings/:id/remove_home_image", to: "paintings#remove_home_image", as: "remove_home_image"

  match 'auth/:facebook/callback', to: 'sessions#facebook'

  match 'auth/failure', to: redirect('/')

end

app/models/category.rb
class Category < ActiveRecord::Base
  
  has_and_belongs_to_many :products
  has_and_belongs_to_many :sold_products
  has_many :paintings, as: :paintable
  belongs_to :featured_painting, class_name: "Painting", foreign_key: :featured_painting_id

  validates :name, presence: true
  

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_filter :initialize_cart, only: [:show]
  def index
    @categories = Category.order("id DESC").page(params[:page]).per(25)
    render
  end

  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @pros = @category.products.order('id DESC')
    @sold_products = @category.sold_products.order('id DESC')
    products = @pros + @sold_products
    @products = Kaminari.paginate_array(products).page(params[:page]).per(15)
    @paintings = @category.paintings
  end

  def new
    @category = Category.new(params[:category])
  end
  
  def create
    if is_admin?
      @category = Category.new(params[:category])
    end
    if
     @category.save
     redirect_to categories_path
    end
  end

  def edit
    @category = Category.find(params[:id])

  end

  def update
    @category = Category.find(params[:id])
    if @category.paintings.present?
    end
    @category.update_attributes(params[:category])
    redirect_to category_path(@category), :notice => "updated"
  end

  def delete

  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
  end
  
  #this is probly not necisary any more. in leu products should have a primary_painting_id
  #better for things to run through the update method.
  def update_featured_painting
    @painting = Painting.find(params[:painting_id])
      @cat = @painting.category
      @cat.update_attributes(featured_painting_id: @painting.id)
    if @cat.save
      redirect_to category_path(@cat)
    end
  end

  private

    def initialize_cart
      @user = current_user
      if @user.present?
        if @user.carts.present?
          @cart = @user.carts.last
        else
          @cart = @user.carts.new(params[:cart])
          @cart.save
        end
      end
  end

end

app/views/categories/_drop_down.html.erb
          <div>
                <div class="span3">
                  <div id="drop-down" >
                    <% Category.all.each do |cat| %>
                      <ul class="name">
                        <%= link_to cat.name, category_path(cat), class: 'name-cat' %>
                      </ul>
                    <% end %>
                  </div>
                </div>
          </div>

app/views/categories/_form.html.erb
<%= form_for @category, :html => {:multipart => true } do |f|  %>
  <p>
  <%= f.label :name, "Category Name" %></br>
  <%= f.text_field :name, required: true %>
  </p>
  <p>
  <%= f.label :description, "Description" %></br>
  <%= f.text_field :description %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/categories/_search_drop_down.html.erb
             <div class="span12">
               <div id="bottom" >
                 <% Category.all.each do |cat| %>
                   <div class="name">
                     <h6><%= link_to cat.name, category_path(cat) %></h6>
                  </div>
                 <% end %>
               </div>
             </div>

app/views/categories/delete.js.erb
$("#painting-<%= @category.id %>").remove()

app/views/categories/destroy.js.erb
$("#product-<%=@product.id%>").remove() 

app/views/categories/edit.html.erb
Edit
<%= render partial: "categories/form" %>

app/views/categories/index.html.erb
<div id="mid_component">
  <div class="row-fluid">
    <% @categories.each do |c| %>
      <div id="painting-holder">
        <div class="span4">
            <%= link_to c.name, category_path(c) %></br>
            <%= c.description %></br>
            <%= link_to (image_tag c.featured_painting.try(:image_url, :thumb )), category_path(c) %></br>
          <% if current_user && is_admin?%>
            <%= link_to "Edit", edit_category_path(c) %>
            <%= link_to 'Delete', c, data: {confirm: "Are you sure you want to delete #{c.name}", method: :delete, remote: true } %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/index.js.erb
/*$('#drop-down').show();
$('#drop-down').on('mouseexit', function() {
  (this).hide();
});

app/views/categories/new.html.erb
<h1> Categories/new </h1>
  <div class="mid_component" >
  <%= render :partial => "categories/form" %>
</div>

app/views/categories/show.html.erb
<% content_for :met_description do %>
  <meta name="description" content="Artwork in the <%= @category.name %> collection. <%= @category.description %> ">
<% end %>

<!--  <div class="cat-search">
    <div class="span4 offset2">
      <div id="cat2">
        <%= link_to "Search by Category", '#', class: "h-head" %>
      </div>
      <div>
        <%= render partial: "categories/search_drop_down"%>
      </div>
    </div>
    <div class="span2">
      <h3>Or</h3>
    </div>
    <div class="span4">
      <div class="prod_search">
        <%= render partial: "products/products_search"%>
      </div>
    </div>
  </div> -->


<div class="row">
  <h2 class="span6 offset4 h-head">Lisa Luree's '<%= @category.name %>' collection</h2>
</div>
<div class="row">
  <h5 class="span10 offset2 cat-description"><%= @category.description if @category.description %></h5>
</div>
  <div class="span12">
    <div class="mid_component">
      <% if @products.present?%>
        <%= render partial: "products/display_products" %>
      <% else %>
        Sorry, there are no products here.
      <% end %>
    </div>
  </div>